### ISSUE TITLE
An update to version 1.3.77 is available, but when installing, Visual Studio thinks it is already installed

### ISSUE THREAD

**Issue by reduckted** [madskristensen/PkgdefLanguage#2]
### Description

Version 1.3.77 appears in the list of extension updates, but when the update runs, Visual Studio says that the extension is already installed. 

The update list in Visual Studio:
![image](https://user-images.githubusercontent.com/10321525/149130396-097c1cf8-b822-49d7-abc7-18e785f177f5.png)

When the update is installed:
![This extension is already installed to all applicable products](https://user-images.githubusercontent.com/10321525/149130424-6c078a14-ed6d-47db-891f-26b4ffbb6a6a.png)

I'm not sure if this is specific to this extension, or whether it's a problem with Visual Studio, but this is the only extension that I'm witnessing this behavior with. 

I'm running VS 17.1.0 Preview 2.0, but if I remember correctly, I was also seeing the update repeatedly available on a different machine that is _not_ running a preview version.

### Steps to reproduce
1. Open _Manage Extensions_ and select _Updates_. _Pkgdef Language_ appears in the list.
2. Click _Update_, then _Close_.
2. Close Visual Studio. The update will start.
3. The VSIX Installer says that the version is already installed.

**Expected behavior:**

The update installs successfully.

**Actual behavior:** 

The update doesn't install, but continues to appear in the list of extensions to update.

**Comment by madskristensen** [comment]
It happens when VS automatically installs a new version in the background of the running instance, but hasn't removed it from the Updates tab. I think this only occurs when there are multiple uploads of a new version multiple times a day, and VS gets caught in between. I've been uploaded a lot recently

**Comment by kevison** [comment]
I ran into this problem yesterday too and posted this in StackOverflow https://stackoverflow.com/questions/70669679/vs-2022-pkgdef-extension-update-fails.

**Comment by madskristensen** [comment]
If you open the extension manager dialog now, is the issue resolved? You may need to restart VS first. If it's fixed, then it's because I was uploaded too rapidly

**Comment by kevison** [comment]
I restarted VS 2022 and tried it again... Nope.... still get the same problem.

**Comment by reduckted** [comment]
Could this be caused by this recent change?

https://github.com/madskristensen/PkgdefLanguage/commit/be28d095340f9a367e71b9ab04ae41e21b98fd3a#diff-e97da5900a266cc3573f6423128d8814a07307838e9738ec09e657f9cc8719adL13-R13

**Comment by madskristensen** [comment]
Ahh, yes perhaps that's the problem. I could make it AllUsers=true again

**Comment by reduckted** [comment]
I think `AllUsers=false` is the better option because extensions that are installed for all users cannot be updated automatically (unless they are signed): https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-update-a-visual-studio-extension?view=vs-2022#to-publish-an-update-of-an-extension

![image](https://user-images.githubusercontent.com/10321525/149429856-644c8094-1e54-4c13-a108-04be1c699349.png)


Uninstalling the extension and re-installing it seems to have fixed the problem.

**Comment by madskristensen** [comment]
The VS extensibility team is working on a fix for when a extension goes from _per-machine_ to _per-user_, It will hopefully be in the next update to VS 2022

**Comment by madskristensen** [comment]
I think this was fixed a while ago now. Closing
